name: Deploy Next.js Static Export to GitHub Pages

on:
  push:
    branches: ["main"]
  # Manually trigger this workflow from the GitHub Actions tab
  workflow_dispatch:

# Sets necessary GitHub environment permissions to securely build and publish code
permissions:
  contents: read
  pages: write
  id-token: write

# Prevents concurrent deployments from overwriting each other
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # -------------------------
  # BUILD
  # -------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Detect Package Manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager (missing package-lock.json)" >> $GITHUB_ERROR
            exit 1
          fi

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Pages Infrastructure
        uses: actions/configure-pages@v5
        with:
          # Hooks Next.js asset subpaths 
          static_site_generator: next

      - name: Install Dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Compile and Export Static Next.js Application
        env:
          NEXT_PUBLIC_LOCAL_API_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_LOCAL_API_GRAPHQL_URL }}
          NEXT_PUBLIC_LOCAL_API_URL: ${{ secrets.NEXT_PUBLIC_LOCAL_API_URL }}
        run: ${{ steps.detect-package-manager.outputs.runner }} next build

      - name: Pack Static Assets Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Targets the default static folder generated by Next.js 'output: export'
          path: ./out

  # -------------------------
  # DEPLOY
  # -------------------------
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish Build Artifact to GitHub Pages Live Server
        id: deployment
        uses: actions/deploy-pages@v4
